# Generated by Django 4.2.6 on 2024-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_mx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
