# Generated by Django 4.2.6 on 2024-02-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aero_mx', '0003_rename_user_hangar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangar', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
